export const tableSchema = [
  { accessorKey: "profile", header: "Name", type: "profile" },
  { accessorKey: "status", header: "Status", type: "badge" },
  { accessorKey: "role", header: "Role", type: "filter" },
  { accessorKey: "email", header: "Email" },
  { accessorKey: "age", header: "Age", type: "sortable" },
  { accessorKey: "teams", header: "Teams", type: "tags" },
];

export const tableData = [
  {
    profile: {
      name: "Alice Brown",
      username: "@aliceb",
      img: "https://randomuser.me/api/portraits/women/10.jpg",
    },
    status: "Working",
    role: "Software Engineer",
    email: "aliceb@company.com",
    age: 30,
    teams: ["Development", "Backend", "Security"],
  },
  {
    profile: {
      name: "Michael Johnson",
      username: "@michaelj",
      img: "https://randomuser.me/api/portraits/men/11.jpg",
    },
    status: "On Leave",
    role: "Data Scientist",
    email: "michaelj@company.com",
    age: 34,
    teams: ["AI/ML", "Research", "Data Analysis"],
  },
  {
    profile: {
      name: "Sophie Williams",
      username: "@sophiew",
      img: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    status: "Working",
    role: "UI/UX Designer",
    email: "sophiew@company.com",
    age: 27,
    teams: ["Design", "Product", "Marketing"],
  },
  {
    profile: {
      name: "Daniel Lee",
      username: "@daniell",
      img: "https://randomuser.me/api/portraits/men/13.jpg",
    },
    status: "On Leave",
    role: "Frontend Developer",
    email: "daniell@company.com",
    age: 29,
    teams: ["Web Development", "React", "Design"],
  },
  {
    profile: {
      name: "Emma Davis",
      username: "@emmad",
      img: "https://randomuser.me/api/portraits/women/14.jpg",
    },
    status: "Working",
    role: "Software Engineer",
    email: "emmad@company.com",
    age: 32,
    teams: ["Marketing", "Social Media", "Content"],
  },
  {
    profile: {
      name: "James Wilson",
      username: "@jamesw",
      img: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    status: "Working",
    role: "Software Engineer",
    email: "jamesw@company.com",
    age: 36,
    teams: ["Infrastructure", "Security", "Cloud"],
  },
  {
    profile: {
      name: "Olivia Martin",
      username: "@oliviam",
      img: "https://randomuser.me/api/portraits/women/16.jpg",
    },
    status: "On Leave",
    role: "Software Engineer",
    email: "oliviam@company.com",
    age: 31,
    teams: ["Human Resources", "Recruitment"],
  },
  {
    profile: {
      name: "William Anderson",
      username: "@williamA",
      img: "https://randomuser.me/api/portraits/men/17.jpg",
    },
    status: "Working",
    role: "Backend Developer",
    email: "williamA@company.com",
    age: 33,
    teams: ["API Development", "Node.js", "Database"],
  },
  {
    profile: {
      name: "Charlotte Thompson",
      username: "@charlottet",
      img: "https://randomuser.me/api/portraits/women/18.jpg",
    },
    status: "Working",
    role: "Software Engineer",
    email: "charlottet@company.com",
    age: 28,
    teams: ["SEO", "Content Strategy", "Marketing"],
  },
  {
    profile: {
      name: "Benjamin Harris",
      username: "@benjaminh",
      img: "https://randomuser.me/api/portraits/men/19.jpg",
    },
    status: "On Leave",
    role: "Product Owner",
    email: "benjaminh@company.com",
    age: 37,
    teams: ["Product", "Business", "Strategy"],
  },
  {
    profile: {
      name: "Ava White",
      username: "@avaw",
      img: "https://randomuser.me/api/portraits/women/20.jpg",
    },
    status: "Working",
    role: "QA Engineer",
    email: "avaw@company.com",
    age: 29,
    teams: ["Testing", "Automation", "Development"],
  },
  {
    profile: {
      name: "Henry Roberts",
      username: "@henryr",
      img: "https://randomuser.me/api/portraits/men/21.jpg",
    },
    status: "On Leave",
    role: "Cybersecurity Analyst",
    email: "henryr@company.com",
    age: 40,
    teams: ["Security", "Threat Analysis"],
  },
  {
    profile: {
      name: "Mia Clark",
      username: "@miac",
      img: "https://randomuser.me/api/portraits/women/22.jpg",
    },
    status: "Working",
    role: "Project Manager",
    email: "miac@company.com",
    age: 35,
    teams: ["Management", "Development"],
  },
  {
    profile: {
      name: "Ethan Lewis",
      username: "@ethanl",
      img: "https://randomuser.me/api/portraits/men/23.jpg",
    },
    status: "On Leave",
    role: "Project Manager",
    email: "ethanl@company.com",
    age: 38,
    teams: ["Infrastructure", "Cloud", "DevOps"],
  },
  {
    profile: {
      name: "Isabella Walker",
      username: "@isabellaw",
      img: "https://randomuser.me/api/portraits/women/24.jpg",
    },
    status: "Working",
    role: "Business Analyst",
    email: "isabellaw@company.com",
    age: 34,
    teams: ["Business", "Product", "Strategy"],
  },
  {
    profile: {
      name: "Logan Hall",
      username: "@loganh",
      img: "https://randomuser.me/api/portraits/men/25.jpg",
    },
    status: "On Leave",
    role: "Tech Lead",
    email: "loganh@company.com",
    age: 39,
    teams: ["Development", "Leadership", "Strategy"],
  },
  {
    profile: {
      name: "Grace Adams",
      username: "@gracea",
      img: "https://randomuser.me/api/portraits/women/26.jpg",
    },
    status: "Working",
    role: "Scrum Master",
    email: "gracea@company.com",
    age: 32,
    teams: ["Agile", "Development", "Management"],
  },
  {
    profile: {
      name: "Lucas Baker",
      username: "@lucasb",
      img: "https://randomuser.me/api/portraits/men/27.jpg",
    },
    status: "Working",
    role: "Database Administrator",
    email: "lucasb@company.com",
    age: 35,
    teams: ["Database", "SQL", "Security"],
  },
  {
    profile: {
      name: "Chloe Green",
      username: "@chloeg",
      img: "https://randomuser.me/api/portraits/women/28.jpg",
    },
    status: "On Leave",
    role: "Project Manager",
    email: "chloeg@company.com",
    age: 27,
    teams: ["Content", "SEO", "Marketing"],
  },
  {
    profile: {
      name: "Ryan Carter",
      username: "@ryanc",
      img: "https://randomuser.me/api/portraits/men/29.jpg",
    },
    status: "Working",
    role: "Project Manager",
    email: "ryanc@company.com",
    age: 31,
    teams: ["Android", "iOS", "Development"],
  },
];
